"""Initial migration

Revision ID: 0485d29094c5
Revises: 
Create Date: 2026-03-06 20:18:13.024380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0485d29094c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('chapters_cnt', sa.Integer(), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gkfeed',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('habits',
    sa.Column('habit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('notify_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('habit_id')
    )
    op.create_table('pomodorostats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('today_cnt', sa.Integer(), nullable=False),
    sa.Column('total_cnt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('roadsettings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('time_focused', sa.Time(), nullable=False),
    sa.Column('time_relax', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('callback', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timezone',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tz', sa.Interval(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('timezone')
    op.drop_table('task')
    op.drop_table('roadsettings')
    op.drop_table('pomodorostats')
    op.drop_table('habits')
    op.drop_table('gkfeed')
    op.drop_table('book')
    # ### end Alembic commands ###
