DEFAULT_COMMANDS = {
    "add_remind": "add remind",
    "feed": "read gkfeed",
    "list": "list of possible bot commands",
    "chatgpt": "ask chatgpt",
    "road": "road to the dream",
    "bomber": "use it for call someone",
    "start_timer": "start timer",
    "admins": "tag all admins",
    "books": "personal book shelf",
    "platonus2indigo": "convert test",
    "dl": "download file",
    "tts": "text to speech",
    "sort_sources": "sort sources",
}
